openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/adeolaadebisi/VCF-CONVERTER/1.0.0
info:
  description: This is a simple API
  version: "1.0.0"
  title: Simple Inventory API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /companyinformation:
    get:
      tags:
        - VCF
      summary: searches inventory
      operationId: getCompanyInformation
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      parameters:
        - in: query
          name: instid
          description: pass an optional search string for looking up inventory
          required: false
          schema:
            type: string
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyInformationResponse'
        '400':
          description: bad input parameter
  /cardholderinformation:
    get:
      tags:
        - VCF
      summary: searches inventory
      operationId: getCardholderInformation
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      parameters:
        - in: query
          name: instid
          description: pass an optional search string for looking up inventory
          required: false
          schema:
            type: string
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardholderInformationResponse'
        '400':
          description: bad input parameter
  /accountinformation:
    get:
      tags:
        - VCF
      summary: searches inventory
      operationId: getAccountInformation
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      parameters:
        - in: query
          name: instid
          description: pass an optional search string for looking up inventory
          required: false
          schema:
            type: string
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountInformationResponse'
        '400':
          description: bad input parameter
  /transactions:
    get:
      tags:
        - VCF
      summary: get transaction information
      operationId: getTransactionInformation
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      parameters:
        - in: query
          name: instid
          description: intitution id of records to fetch
          required: false
          schema:
            type: string
        - in: query
          name: startDate
          description: start date filter for record
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: endDate
          description: end date filter for record
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 50
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionInformationResponse'
        '400':
          description: bad input parameter
  /auth:
    post:
      tags:
        - VCF
      summary: adds an inventory item
      operationId: Authentication
      description: Adds an item to the system
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Authentication'
        description: Inventory item to add
components:
  schemas:
    AuthenticationResponse:
      type: object
      properties:
        access_token:
          type: string
          format: jwt
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJUWFVTRVJORyIsImp0aSI6ImU3ZmQzNjkzLTNlODktNDI0Mi1hNjdhLTE3NGQ3ZThjOWQyZCIsImlhdCI6IjEwLzI4LzIwMjQgMTA6MzM6MjUgQU0iLCJuYmYiOjE3MzAxMTE2MDUsImV4cCI6MTc2MTY0NzYwNSwiaXNzIjoiaHR0cHM6Ly93d3cubGlua2VkaW4uY29tL2luL3NhbXVlbC13YWluYWluYS03MWI3MDkxNzcvIiwiYXVkIjoiU2FtdWVsIFdhaW5haW5hIn0.aVDo7j8v6ckVjWKWciUlT0RhlW68YW3OjUydAitMIXw
        expires_in:
          type: integer
          example: 365

    TransactionInformationResponse:
      type: object
      properties:
        txTrans:
          type: array
          items:
            $ref: '#/components/schemas/TransactionInformation'
          example:
            - loadtransactioncode: '4'
              contractid: '16339'
              postingDate: '2023-10-18 00:00:00'
              retrievalrefnumber: null
              transactionReference: '231017756000042078'
              acquiringbin: '507868'
              cardacceptorid: null
              suppliername: null
              suppliercity: null
              supplierstateprovincecode: null
              supplierisocountrycode: '566'
              supplierpostalcode: null
              sourceamount: '200000.00'
              billingamount: '200000.00'
              sourcecurrencycode: '566'
              merchantcategorycode: null
              transactiontypecode: '00'
              period: '24305'
              billingcurrencycode: '566'
              taxamount: null
              disputeamount: null
              disputereasoncode: null
              disputedate: null
              exratedplength: '2'
              tokenid: '4567'
              accountNumber: '5078683012532895232'
              sequenceNumber: '231017756000042078'
            - loadtransactioncode: '4'
              contractid: '16338'
              postingDate: '2024-09-01 00:00:00'
              retrievalrefnumber: '000000248527'
              transactionReference: '240902368911021820'
              acquiringbin: '507868'
              cardacceptorid: '605153000000001'
              suppliername: '00000000'
              suppliercity: Visa Direct
              supplierstateprovincecode: null
              supplierisocountrycode: '566'
              supplierpostalcode: null
              sourceamount: '200.00'
              billingamount: '200.00'
              sourcecurrencycode: '566'
              merchantcategorycode: '6011'
              transactiontypecode: '00'
              period: '24305'
              billingcurrencycode: '566'
              taxamount: null
              disputeamount: null
              disputereasoncode: null
              disputedate: null
              exratedplength: '2'
              tokenid: '4564'
              accountNumber: '5078683012532895232'
              sequenceNumber: '5078683012532895232'
            - loadtransactioncode: '4'
              contractid: '16338'
              postingDate: '2024-09-01 00:00:00'
              retrievalrefnumber: '000000249434'
              transactionReference: '240910457599472206'
              acquiringbin: '507868'
              cardacceptorid: '605153000000001'
              suppliername: '00000000'
              suppliercity: Visa Direct
              supplierstateprovincecode: null
              supplierisocountrycode: '566'
              supplierpostalcode: null
              sourceamount: '200.00'
              billingamount: '200.00'
              sourcecurrencycode: '566'
              merchantcategorycode: '6011'
              transactiontypecode: '00'
              period: '24305'
              billingcurrencycode: '566'
              taxamount: null
              disputeamount: null
              disputereasoncode: null
              disputedate: null
              exratedplength: '2'
              tokenid: '4564'
              accountNumber: '5078683025065790463'
              sequenceNumber: '240910457599472206'
            - loadtransactioncode: '4'
              contractid: '16338'
              postingDate: '2024-09-01 00:00:00'
              retrievalrefnumber: '000000249432'
              transactionReference: '240910457574972205'
              acquiringbin: '507868'
              cardacceptorid: '605153000000001'
              suppliername: '00000000'
              suppliercity: Visa Direct
              supplierstateprovincecode: null
              supplierisocountrycode: '566'
              supplierpostalcode: null
              sourceamount: '200.00'
              billingamount: '200.00'
              sourcecurrencycode: '566'
              merchantcategorycode: '6011'
              transactiontypecode: '00'
              period: '24305'
              billingcurrencycode: '566'
              taxamount: null
              disputeamount: null
              disputereasoncode: null
              disputedate: null
              exratedplength: '2'
              tokenid: '4564'
              accountNumber: '5078683025065790463'
              sequenceNumber: '240910457574972205'

    TransactionInformation:
      type: object
      required:
        - loadtransactioncode
        - contractid
        - postingDate
        - retrievalrefnumber
        - transactionReference
        - acquiringbin
        - cardacceptorid
        - suppliername
        - suppliercity
        - supplierstateprovincecode
        - supplierisocountrycode
        - supplierpostalcode
        - sourceamount
        - billingamount
        - sourcecurrencycode
        - merchantcategorycode
        - transactiontypecode
        - period
        - billingcurrencycode
        - taxamount
        - disputeamount
        - disputereasoncode
        - disputedate
        - exratedplength
        - tokenid
        - accountNumber
        - sequenceNumber
      properties:
        loadtransactioncode:
          type: string
          example: 4
        contractid:
          type: string
          example: 16339
        postingDate:
          type: string
          example: 2023-10-18 00:00:00
        retrievalrefnumber:
          type: string
          example: null
        transactionReference:
          type: string
          example: 231017756000042078
        acquiringbin:
          type: string
          example: 507868
        cardacceptorid:
          type: string
          example: null
        suppliername:
          type: string
          example: null
        suppliercity:
          type: string
          example: null
        supplierstateprovincecode:
          type: string
          example: null
        supplierisocountrycode:
          type: string
          example: 566
        supplierpostalcode:
          type: string
          example: null
        sourceamount:
          type: string
          example: 200000.00
        billingamount:
          type: string
          example: 200000.00
        sourcecurrencycode:
          type: string
          example: 566
        merchantcategorycode:
          type: string
          example: null
        transactiontypecode:
          type: string
          example: 00
        period:
          type: string
          example: 24305
        billingcurrencycode:
          type: string
          example: 566
        taxamount:
          type: string
          example: null
        disputeamount:
          type: string
          example: null
        disputereasoncode:
          type: string
          example: null
        disputedate:
          type: string
          example: null
        exratedplength:
          type: string
          example: 2
        tokenid:
          type: string
          example: 4567
        accountNumber:
          type: string
          example: 5078683051928165
        sequenceNumber:
          type: string
          example: 231017756000042078
    CompanyInformationResponse:
      type: object
      properties:
        singleCompany:
          $ref: '#/components/schemas/CompanyInformation'
    CompanyInformation:
      type: object
      required:
        - companyID
        - companyName
        - isoCountryCode
        - fiscalYearDate
        - cardType
        - issuerName
        - organizationHierarchyManagementIndicator
      properties:
        companyID:
          type: string
          example: 41
        companyName:
          type: string
          example: Coca-cola
        isoCountryCode:
          type: string
          example: 566
        fiscalYearDate:
          type: string
          example: 12/31
        cardType:
          type: string
          example: 1
        issuerName:
          type: string
          example: Sterling Bank
        organizationHierarchyManagementIndicator:
          type: string
          example: 1
        effectiveDate:
          type: string
          example: 2021-10-20 00:00:00  
    CardholderInformationResponse:
      type: object
      properties:
        cardHolderInformation:
          type: array
          items:
            $ref: '#/components/schemas/CardholderInformation'
          example:
            - companyIdentification: '41'
              cardholderIdentification: '1186'
              firstName: ALTERNATIVE1
              lastName: FINANCE
              isoCountryCode: '566'
            - companyIdentification: '41'
              cardholderIdentification: '1214'
              firstName: CHARGE 1
              lastName: CHARGE
              isoCountryCode: '566'
          

    CardholderInformation:
      type: object
      required:
        - companyIdentification
        - cardholderIdentification
        - firstName
        - lastName
        - isoCountryCode
      properties:
        companyIdentification:
          type: string
          example: 41
        cardholderIdentification:
          type: string
          example: 1186
        firstName:
          type: string
          example: Adeola
        lastName:
          type: string
          example: Adebisi
        isoCountryCode:
          type: string
          example: 566
    AccountInformationResponse:
      type: object
      properties:
        accInfo:
          type: array
          items:
            $ref: '#/components/schemas/AccountInformation'
          example:
            - cardholderId: '1186'
              accountNumber: '5078683012532895232'
              accountOpenDate: '2022-02-01 00:00:00'
              cardType: '1'
              statementType: '3'
              statusCode: '1'
              annualFeeFlag: '0'
              annualFeeMonth: '12'
            - cardholderId: '1214'
              accountNumber: '5078683025065790463'
              accountOpenDate: '2022-02-01 00:00:00'
              cardType: '1'
              statementType: '3'
              statusCode: '1'
              annualFeeFlag: '0'
              annualFeeMonth: '12'
    AccountInformation:
      type: object
      required:
        - cardholderId
        - accountNumber
        - accountOpenDate
        - cardType
        - statementType
        - statusCode
        - annualFeeFlag
        - annualFeeMonth
      properties:
        cardholderId:
          type: string
          example: 1365
        accountNumber:
          type: string
          example: 5078683012532895232
        accountOpenDate:
          type: string
          example: 2022-02-01 00:00:00
        cardType:
          type: string
          example: 1
        statementType:
          type: string
          example: 3
        statusCode:
          type: string
          example: 1
        annualFeeFlag:
          type: string
          example: 0
        annualFeeMonth:
          type: string
          example: 12

    InventoryItem:
      type: object
      required:
        - name
        - password
      properties:
        name:
          type: string
          example: name
        password:
          type: string
          example: password
    Authentication:
      type: object
      required:
        - name
        - password
      properties:
        name:
          type: string
          example: name
        password:
          type: string
          example: password
    Manufacturer:
      required:
        - name
      properties:
        name:
          type: string
          example: ACME Corporation
        homePage:
          type: string
          format: url
          example: 'https://www.acme-corp.com'
        phone:
          type: string
          example: 408-867-5309
      type: object
